services:

  postgres:
    image: postgres:17

    container_name: morpho-postgres

    environment:
      POSTGRES_USER: morpho
      POSTGRES_PASSWORD: morpho
      POSTGRES_DB: morpho

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

metabase:

    image: metabase/metabase

    container_name: morpho-metabase

    ports:
      - "3000:3000"

    depends_on:
      - postgres

volumes:
  postgres_data: