
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'morpho_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'morpho_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  morpho_analytics:
    staging:
      +materialized: view
    marts:
      dimensions:
        +materialized: table
      facts:
        +materialized: table
      risk:
        +materialized: table
